# Generated by Django 5.0.1 on 2024-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
